GrottoCenter/grottocenter-api

assets/js/react/App.jsx
This syntax works both on Chrome and Firefox for using the redux dev tool extension.
=> fix(#115): fix syntax for creating store

api/services/MappingV1Service.js
On the previous PR fixing the quick search, the renaming keys was broken by me (example : the key "bbs title" from Elasticsearch must be renamed "title", "bbs authors" => "authors" etc.). 
I simplified the code renaming the keys, it's cleaner and works properly now.
=> [BBS & mapping service] Fix renaming keys + Fix total number of results returned by Elasticsearch

api/services/MappingV1Service.js, deployDev.sh
In development, we now use the same Elasticsearch & Logstash version as in production. Also, there were breaking changes when passing to v7 (https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html) : I fixed one of these.
=> Bump Elasticsearch version in development (6.5.0 => 7.5.1)

assets/js/react/components/common/Maps/MultipleMarkers.jsx
=> [ENTRY PAGE] Remove fullscreen map control on entry page

assets/js/react/App.jsx
Custom handler for missing translation. 
By default, it shows the stacktrace which is very annoying (it takes a lot of place on the screen).
This handler wrap everything in a collapsed group.
=> [INTL ERRORS] Collapse missing translations

api/controllers/MassifController.js, api/services/CaveService.js, api/services/NameService.js
When a cave has only one entry, it has no name in t_name. 
Instead, its name is the name of its sole entry.
=> [CAVE] Fix empty name for cave

api/policies/tokenAuth.js, assets/js/react/actions/Document.jsx, assets/js/react/helpers/AuthHelper.jsx
Auth token must be in Authorization header instead of in the body request.
=> [AUTH TOKEN] Put auth token in authorization header

api/policies/adminAuth.js
This policy assumes that there is a valid token in req.token which is the case when the request has been proceeded by the tokenAuth policy.
So, use this policy ONLY after using the tokenAuth policy!
=> [POLICIES] Add adminAuth policy

api/controllers/ConvertController.js, assets/js/react/components/common/Maps/main/Convert.jsx
Je n'ai pas cherché à améliorer la fonctionnalité plus que ça. L'idée c'était juste de rerendre le convertisseur (en bas à gauche de la carte) fonctionnel avec les nouvelles données PostGre. 
J'ai juste refactorisé 5-6 fonctions en une seule et corrigé le linting.
Pour faire fonctionner ce code, il faut un nouveau dump de données daté du 24 septembre au minimum (il ajout la table t_crs demandée par cette feature) : je peux le faire passer en privé si besoin.
=> [CONVERT SERVICE] Match new PGSQL data model + fix linting

assets/js/react/components/appli/Document/DocumentForm/stories/_stories.js, assets/js/react/components/appli/Document/DocumentForm/stories/documentFormFakeData.js
The **LanguageSelect** component needs an API call to get all the available languages and, then, it puts them on the Redux store. 
So I deleted it from storybook because it's too complex to fake this API call. We will see later.
=> fix(#371) [DOC SUBMISSION STORIES] Fix IdentifierEditor and LanguageSelect stories

api/controllers/GrottoController.js
Le nombre de partenaires officiels sur la page d'accueil a sauté depuis quelques temps. Voilà le correctif qui utilise le ControllerService au lieu de renvoyer des données brutes.
=> fix(officialPartnersApi) - Use count + controllerService

assets/js/react/pages/DocumentValidation/DocumentsTable.jsx
pathOld (i.e, old url from Grottocenter v2) was added recently by the document's API to the document objects sent. We must hide it in documentValidation by default.
=> [DOC VALIDATION] Hide pathOld attribute by default

api/services/MappingV1Service.js
In the DB, the id can be a string of 5-characters long. We need to trim them because some of them are 3 (or 4)-characters long (DOI, URL...)
=> [DOCUMENT API] Trim document identifier type id

api/controllers/DocumentController.js, assets/js/react/pages/DocumentSubmission.jsx, assets/js/react/pages/DocumentValidation/index.jsx
It was impossible to edit 2 documents in a row because the api messages were not reset in the Redux store and, thus, the document validation was constantly reloading.
=> [DOC EDIT] Fix bug when editing 2 documents in a row

assets/js/react/components/common/card/RandomEntryCard.jsx
The previous code was crashing the whole app by trying to translate "hour(s)" and "minute(s)" when displaying a duration. It's not needed : "13h 24m" is understandable in all languages easily.
=> fix(#181) [RANDOM ENTRANCE] (x) hours is not translated

api/controllers/DocumentController.js, assets/js/react/pages/DocumentValidation/DocumentsTable.jsx
Previously, when a hidden column was marked as "visible" it broke the table by putting data in the wrong column.
Also, using localeCompare instead of a simple "sort" is more intl-friendly.
Also, when fetching all documents, if there is no document found, an appropriate error is returned.
=> [DOC VALIDATION] Fix sort columns by label translated + fix findAll documents API error message

assets/js/react/pages/DocumentDetails/index.jsx, assets/js/react/pages/DocumentDetails/transformers.js
Pour les régoins et les sujets, dans **transformers.js**, il est nécessaire de conserver l'objet entier (et pas juste une string). 
En effet, on traduit grâce à l'attribut **code** mais si la traduction n'existe pas, il faut utiliser l'attribut **subject** (pour un sujet) ou l'attribut **name** (pour une région)
=> [DOC DETAILS] Translate regions, subjects & document type

assets/js/react/features/QuickSearch.jsx
"type" of an entrance result is "entrance" now, not "entry".
=> fix(#435) [QUICK SEARCH] Click on entrance result redirection

assets/js/react/components/common/Table/TableHead.jsx, assets/js/react/pages/Admin/UserList.jsx, assets/js/react/pages/DocumentValidation/DocumentsTable.jsx
For UserList and DocumentsTable only: if a column's ID starts with `@` it will be automatically added to the default hidden columns.
Closes issue #500
=> feat(cleanup): hides the columns prefixed with `@`

api/controllers/DocumentController.js
When someone validates or refuses a document, we now add his / her id to the document validator field.
=> #497 [DOC VALIDATION] Missing validator id

api/helpers/check-right.js
A right in the database has ALWAYS the following syntax : 
**ENTITY - ACTION**
**Examples:**
- *Caver - view any*
- *Cave - delete  any*
=> [RIGHT CHECKER] Fix right syntax research in database + log error

api/controllers/EntranceController.js, api/controllers/v1/EntranceController.js, api/models/TEntrance.js, api/services/ControllerService.js, api/services/ElasticsearchService.js, apiV1.yaml, config/policies.js, config/routes.js
Where an entrance is deleted, the controller checks if :
- the user can delete it
- the entrance is not already deleted
Then it performs the delete action, which fires the historization database triggers. Finally, it tries to delete the entrance from Elasticsearch: this can fail silently because I don't want to return an error to the user just for this. Additionally, Elasticsearch is updated every day. If a deletion doesn't work, it will be performed in the incoming 24h.
Also, I have deleted the *ElasticsearchService.updateIndex()* method. updateIndex() was never used and can't work in the way it's implemented (automatically deduce the action to perform by looking only at the request).
=> [ENTRANCE API] Add delete route

api/controllers/EntranceController.js
It can't be handled in the model because it's an association with the t_geology table.
=> [ENTRACE API] Add geology default value

api/controllers/EntranceController.js, api/policies/facultativeTokenAuth.js, api/services/RightService.js, apiV1.yaml, config/policies.js
1. Client is a visitor => hide the entrance => return a "forbidden" response
2. Client is an authenticated user => show the entrance without longitude, latitude & locations
3. Client is an authenticated administrator => show the whole entrance
I have added a new policy called *facultativeTokenAuth*. It parses the auth token if present. If it is not present, it keeps going.
=> [ENTRANCE API] For sensitive entrances, show info depending on user rights

api/controllers/NameController.js, api/controllers/v1/NameController.js, api/models/TEntrance.js, api/services/MappingV1Service.js, apiV1.yaml, config/policies.js, config/routes.js
- N'importe qui peut rendre un name "main".
- Tous les autres names se référant à la même entité (cave, entrance, massif, grotto, point) voient leur isMain passer à `false`. Cela permet de préserver l'unicité du isMain pour une entité donnée.
=> [NAME API] Set as main api route

api/controllers/DocumentController.js
Fix the issue that prevents a new document to be searchable if the publication date is not provided.
=> fix(newDoc): store null publication date

api/services/ElasticsearchService.js
- Add french quote mark and backslash to the special characters we must ignore
- Remove the last dot of a search query, if there is any. If you add it, even if the field (title or description) possesses such dot at the end, it couldn't be found.
=> fix(search): add special char to ignore

config/security.js
Autorise la présence du header authorization pour les requêtes venant du nouveau front (ou autres). Nécessaire pour pouvoir effectuer des actions qui nécessitent d'être connecté.
=> fix(cors): allow authorization header

api/services/NameService.js
Si la cave n'a pas de noms, on ne pouvait pas récupérer celle de l'entrée, car entrance n'est pas un attribut de cave à moins de populate cave (mais c'est pas toujours le cas, notamment dans find de DocumentController)
=> fix(nameService): fix retrieve cave name

api/controllers/CaverController.js, api/controllers/EntranceController.js, api/services/CaverService.js, api/services/ErrorService.js, api/services/MappingV1Service.js
I think it will be a good idea to refactor a lot of code similar to `CaverService.getCaver()` new function. 
The use of the `defaultOrmHandler()` is very convenient (thanks to Axel for inspiring me !)  + we will be able to deep populate a lot of things easily.
=> [ENTRANCE API] Populate all authors for child data

api/controllers/DocumentController.js, api/controllers/v1/DocumentController.js, api/services/DescriptionService.js, api/services/DocumentService.js, apiV1.yaml, config/routes.js
Fix #644
Feature is not recursive anymore : just find children and grandchildren. This is enough for the main use case which is "When an user is viewing a Collection, he needs to view the issues and the articles (children and grandchildren)".
`GET /documents/:id` does not return children anymore. You need to call `GET /documents/:id/children` to get them.
=> [CHILD DOC] Improve document children performance

api/controllers/EntranceController.js, apiV1.yaml
- Check required parameters
- Simplify parameters when only an id is needed. For example:
```json
{
"cave": {
"id": 5
}
}
```
becomes
```json
{
"cave": 5
}
```
Here is a full example I used during testing: 
```json
{
"name": {
"language": "fra",
"text": "L'entrée XYZ"
},
"cave": 5,
"country": "FR",
"description": {
"body": "Ceci est une description de cette incroyable entrée.",
"language": "fra",
"title": "Titre de la description de l'entrée"
},  
"location": {
"body": "Prenez à droite après le premier virage sur la D10 direction Dupond. Contournez le grand chêne par la gauche et baissez les yeux : vous y êtes!",
"language": "fra"
},
"depth": 42,
"geology": "Q35758",
"isDiving": true,
"length": 530,
"longitude": -83.980479240417,
"latitude": 22.440979208779,
"temperature": 8.36
}
```
=> [ENTRANCE] Improve create entrance method

api/controllers/CaveController.js, api/controllers/v1/CaveController.js, api/services/CaveService.js, assets/swaggerV1.yaml
- multiple descriptions are now allowed (you must always send an array, even for one description)
- name and descriptions improved. Now using full objects.
- "id" key must be omitted: just put the id of the data.
JSON used: 
```json
{
"depth": 42,
"descriptions": [
{
"body": "There are many rocks.",
"language": "eng",
"title": "Geology"
},
{
"body": "It's wet",
"language": "eng",
"title": "Hydrology"
},
{
"body": "Very beautiful",
"language": "eng",
"title": "First gallery"
}
],
"documents": [
109,
161,
191
],
"isDiving": true,
"latitude": 22.440979208779,
"length": 530,
"longitude": -83.980479240417,
"massif": 4,
"name": {
"text": "La Cavité XYZ",
"language": "eng"
},
"temperature": 8.36
}
```
=> [CAVE] Fix & improve createCave route

api/controllers/FileFormatController.js, api/controllers/GeoLocController.js, api/controllers/v1/GeoLocController.js, api/services/GeoLocService.js, config/policies.js, config/routes.js
Fix #690
Networks = cave with nb of entrances > 1
Le fichier `routes.js` a été nettoyé. J'ai marqué des routes comme "deprecated" en indiquant quelle route utiliser à la place. Il faudra voir quand est-ce qu'on les supprimera. Il serait judicieux d'envoyer un email aux personnes utilisant notre API pour les prévenir avant la suppression (cf #647).
J'ai totalement refactorisé tous les fichiers de Geoloc, il y en avait bien besoin : beaucoup de Promise().then().error() alors que le await devient la norme dans toute l'API.
=> [GEOLOC] Return networks instead of caves

api/responses/badRequest.js, api/responses/forbidden.js, api/responses/ok.js, api/responses/serverError.js, api/responses/unauthorized.js
**Issue**
When an error response was sent, the API send the `data` variable always "as is". But, in most of the cases, `data` is a plain string and thus, this caused a JSON parse error.
**Solution**
The error response check if `data` is a string or not. If it's a string, it converts it to a JSON object, with a "message" key.
=> [ERROR RESPONSES] Convert to json when user wants json

.github/workflows/build.yaml, .husky/commit-msg, .husky/pre-commit, .nvmrc, AWSDeployProd.sh, AWSRestartProd.sh, AWSStopProd.sh, README.md, docker/node.Dockerfile, package-lock.json, package.json
Resolve #714
- Node has been bumped to v16.14.2 (latest lts) everywhere, including in production EC2 instance using nvm.
- I have created a .nvmrc file here and in production to specify which version we are using.
For eslint and prettier, they will be updated for #739. I want to completely reset the (bad) linting of the API.
=> 714 [PACKAGES] Update some packages manually to new major versions

.github/workflows/build.yaml
**TL,DR**
Unlike npm install, npm ci will look in your package-lock.json to install all the dependencies with the exact version.
npm ci will never modify your package-lock.json. It does however expect a package-lock.json file in your project.
https://docs.npmjs.com/cli/v8/commands/npm-ci
https://betterprogramming.pub/npm-ci-vs-npm-install-which-should-you-use-in-your-node-js-projects-51e07cb71e26
https://stackoverflow.com/questions/52499617/what-is-the-difference-between-npm-install-and-npm-ci
Github action now runs eslint and prettier to reject pull request not correctly formatted. It does NOT fix the issues, it just shows them: it's the developer responsibility to check them and fix them.
=> [CI / GH ACTIONS] Use npm ci instead of npm install + add Prettier and ESLINT in GH actions

api/services/ElasticsearchService.js, logstash.conf
The id field being a serial, our wildcard search system didn't work on it. Now Logstash casts them as a varchar to allow this.
=> [SEARCH] allow to search on id by casting them to string

api/controllers/v1/cave/delete-one.js, api/controllers/v1/entrance/delete-one.js, api/controllers/v1/massif/delete-one.js, api/controllers/v1/organization/delete-one.js
Les massifs et entrées de cavité n'étaient pas automatiquement supprimées d'Elasticsearch à leur suppression : c'est désormais le cas avec cette PR.
=> [DELETE] Fix elasticsearch deletions

api/helpers/log-response.js, config/log.js
Fix #982
Always log at "info" level, even in production.
=> fix(#982): bump prod log level to info

api/controllers/v1/document/multiple-validate.js, api/controllers/v1/document/update.js, api/models/JDocumentLanguage.js, api/services/DocumentService.js
Fix #1088
Multiple doc validation was not handling the doc language correctly. 
`TDocument.updateOne()` doesn't handle collections (languages is a document collection).
`replaceCollection()` must be used for this case.
I also refactored the `updateDocument()` method, moving it from controller to service. 
Since only one language per document is used, I have set the `JDocumentLanguage.isMain` to true by default.
=> fix(#1088): fix doc language edit when doc is validated

api/controllers/v1/document/import-rows.js, api/services/DocumentService.js
Fix #1086
Previously, when a document with an identifier as "URL" was created, if the URL provided was a file, it was automatically downloaded. 
So I added a `shouldDownloadDistantFile` flag set to false by default in the `DocumentService.createDocument()` method.
The previous behaviour causes us trouble because we don't know if the user creating the document can download the file and put it on the Grottocenter's server.
Only the administrators using the import CSV feature can download the files because they have asked the authorization before importing the CSV file.
Can't be tested easily in test environment.
=> fix(#1086): download doc file only from CSV import

api/controllers/v1/comment/create.js, api/controllers/v1/comment/update.js, api/controllers/v1/description/create.js, api/controllers/v1/description/update.js, api/controllers/v1/history/create.js, api/controllers/v1/history/update.js, api/controllers/v1/location/create.js, api/controllers/v1/location/update.js, api/controllers/v1/rigging/create.js, api/controllers/v1/rigging/update.js, api/services/mapping/converters.js
Fix #1092 : notification related entity link (entrance of a description, entrance of a location, cave of a history etc.).
In the client, when a notification about a description (for example) is displayed, the client doesn't know where to redirect the user when he clicks the notification : there is no "description" page. Instead, the client search a related entity in the notification, such an entrance, and redirects the user to it.
During #1074, the notification converter has been updated. It stopped to return the related entity of a notification. 
Create new converters for description, location, comment, rigging and history (simple & complete ones) : 
- simple ones don't return the related entity
- complete ones do
`toNotification` uses `toDescription, toLocation, toRigging, toHistory` …
=> [NOTIFICATIONS] Fix related entity link

api/controllers/v1/cave/find.js, api/controllers/v1/document/find.js, api/controllers/v1/entrance/find.js, api/controllers/v1/massif/find.js, api/controllers/v1/organization/find.js, api/models/TDocument.js, api/models/TGrotto.js, api/models/TMassif.js, api/services/ElasticsearchService.js, api/services/mapping/converters.js, api/services/mapping/utils.js, logstash.conf, test/integration/2_utils/toList.test.js
This PR fix and improve the deleted concept in the grottocenter API : 
- add missing `is_deleted` property on multiple models (and return it in API response)
- add missing `redirect_to` property on massif (and return it in API response)
- add a way to filter the `is_deleted` entities with the `toList` function of the utils.
- filter "deleted" entites returned by most routes (using the toList function above in the converters)
- improve the logstash file to save the "deleted" state of every items from ES (fix #1075)
- imporve the logstash file to store the country names in whole possible language  (fix #588)
- add a "toDeletedXXX" converter for all the main entities which can be marked as deleted (Cave, Massif, Document, ...)
=> feat(search): properly handle deleted entrance

api/models/TMassif.js
Remove the obsolete max length contraint on the polygone massif field.
this was useful when the polygone was a KML (string in DB). Now it is stored as a geography with no size limit in DB.
=> feat(massif): remove 2000 length constraint on polygone

api/services/DataQualityComputeService.js
Add distinct in sql request to avoid duplicated entrances in the resullt of the request retrieving the entrances of a country. 
We didn't see this error before because we didn't realize that an entrance could be in two different massifs.
=> fix duplicated entrances for a countries

api/controllers/v1/account/change-email.js, api/controllers/v1/account/forgot-password.js, api/controllers/v1/auth/sign-up.js, api/services/AuthService.js
This is to :
- prevent duplicate email addresses in the t_caver table with different case
- make login easier event if the case of the email provided during login is not the same as the DB.
In addition to this code change, the following Query will need to be run in DB : 
```
update public.t_caver set mail = LOWER(mail);
```
Fix #1154
=> improvement(login): caver email always as lowercase

api/controllers/v1/entrance/update.js, api/services/EntranceService.js
Fix bad naming of the `country` column name with waterline
=> fix(entrance): use coordinates to set country

api/controllers/v1/document-duplicate/find.js
Fix document duplicate display error when the column `dc:language` was not present or mistyped during CSV import.
Like the with this [CSV](https://github.com/GrottoCenter/grottocenter-front/files/11289276/test3lignes.EchoKarst.csv)
=> Fix document duplicate display error

api/controllers/v1/cave/update.js, api/controllers/v1/change/get-recent.js, api/controllers/v1/document/multiple-validate.js, api/controllers/v1/entrance/update.js, api/controllers/v1/massif/create.js, api/controllers/v1/massif/update.js, api/controllers/v1/organization/update.js, api/models/TLastChange.js, api/services/CaveService.js, api/services/DocumentService.js, api/services/EntranceService.js, api/services/GrottoService.js, api/services/RecentChangeService.js, assets/swaggerV1.yaml, config/policies.js, config/routes.js, sql/0_tables.sql, sql/0_triggers.sql
Save the latest contributions and add a new endpoint to retrieve them
https://github.com/GrottoCenter/grottocenter-front/issues/384
A new table is created to save the latest changes: `t_last_change`.
This new table is populated using DB triggers on the different entities.
Only the _create_ and _update_ changes are saved, the _delete_ and document validation changes are not saved.
The change for a document is only saved when it is validated
For (sub) entities like `location`, `rigging` or `history` the reference to the related main entities is also saved (entrance or document)
The Name of the entity (or related entity) is also retrieved when the change is made to conserve the name change history
The change list from the database is not returned directly, to be more concise and useful …
=> Save and expose the latest contributions

api/controllers/v1/caver/get-db-export.js, api/controllers/v1/document/create.js, api/controllers/v1/document/multiple-validate.js, api/controllers/v1/document/update.js, api/services/DocumentService.js, api/services/FileService.js, api/services/mapping/converters.js, assets/dbExport/license_en.txt, assets/dbExport/license_fr.txt, config/bootstrap.js, config/policies.js, config/routes.js, package-lock.json, package.json, script/dbExport/cave.js, script/dbExport/document.js, script/dbExport/entrance.js, script/dbExport/massif.js, script/dbExport/organization.js, script/dbExport/utils.js, script/periodicDbExport.js, test/integration/1_services/FileService.test.js
Implement #1118
Use paginated queries to export all data for each main collection of the database.
For sensitive entrances the location are removed. For user only the nickname and id are keeped
Given the current size the database the full export should takes about a minute
During the export, nodejs streams and async generators are used to make sure the memory usage remains reasonable
The exported files are in JSON format. In form of big arrays of objects where each item is on a separate line.
To reduce the size, all files are bundled into a zip archive. Its current size is about 29Mo
At the end, the archive is uploaded into a private Azure storage container to make it available. 
Leader users can retrieve a download link using a new endpoint GET /api/v1/cavers/export/db. The pre-signed …
=> Periodically exports the database
