GrottoCenter/grottocenter-api

- assets/js/App.jsx
- assets/js/Config.jsx
- assets/js/actions/LatestBlogNews.jsx
- assets/js/components/NewsCard.jsx
- assets/js/components/homepage/LatestBlogNewsSection.jsx
- assets/js/containers/LatestBlogNews.jsx
- assets/js/reducers/LatestBlogNewsReducer.jsx
https://github.com/GrottoCenter/Grottocenter3/issues/23
> improv(#23): news are now not loaded in main component page

- assets/js/react/actions/SideMenu.jsx
- assets/js/react/components/appli/ComplexMenuEntry.jsx
- assets/js/react/components/appli/SideMenu.jsx
- assets/js/react/components/appli/SimpleMenuEntry.jsx
- assets/js/react/containers/ComplexMenuEntryConnector.jsx
- assets/js/react/containers/SimpleMenuEntryConnector.jsx
- assets/js/react/reducers/SideMenuReducer.jsx
> #42: Implements clicks on side menu

- assets/js/react/components/common/GCMap.jsx
> #56 remove leaflet autopan

- assets/js/react/components/common/GCMap.jsx
- assets/js/react/components/common/Spinner.jsx
- assets/js/react/conf/Config.jsx
> #50 Rework map localization

- assets/js/react/components/appli/AppFooter.jsx
- assets/js/react/components/appli/AppToolbar.jsx
- assets/js/react/components/appli/HeaderTitle.jsx
- assets/js/react/components/appli/SideMenu.jsx
- assets/js/react/components/common/GCLogo.jsx
- assets/js/react/components/homepage/Association.jsx
- assets/js/react/components/homepage/Header.jsx
- assets/js/react/components/homepage/Publisher.jsx
- assets/js/react/conf/Config.jsx
> feat(#49): add logo on appli header and create a generic logo component

- assets/js/react/components/appli/SideMenu.jsx
- assets/js/react/components/appli/SideMenuBurger.jsx
- assets/js/react/components/common/CheckPermission.jsx
- assets/js/react/conf/Rights.jsx
> feat(#69): hide side menu using permission check

- api/services/GeoLocService.js
- assets/js/react/App.jsx
- assets/js/react/actions/Map.jsx
- assets/js/react/components/common/GCLink.jsx
- assets/js/react/components/common/GCMap.jsx
- assets/js/react/components/common/MapEntryPopup.jsx
- assets/js/react/components/common/Searchbar.jsx
- assets/js/react/components/homepage/Header.jsx
- assets/js/react/conf/Config.jsx
- assets/js/react/containers/MapContainer.jsx
- assets/js/react/containers/QuicksearchContainer.jsx
- assets/js/react/reducers/MapReducer.jsx
> feat(#51): focus on entry and map popup for entry

- README.md
- package.json
Fix the script to start the hot-reloading for development. It now hot-reload front and back.
> fix(#117): Fix script for hot-reloading and update Readme.md

- assets/js/react/components/appli/ApiDetail.jsx
- assets/js/react/components/pages/Application.jsx
- assets/js/react/components/pages/Swagger.jsx
- assets/js/react/conf/Config.jsx
- config/locales/en.json
- config/locales/fr.json
- package-lock.json
- package.json
> Fix embedded Swagger UI

- apiV1.yaml
- assets/js/react/components/admin/Tools.jsx
- assets/js/react/components/appli/SideMenu.jsx
- assets/js/react/conf/Config.jsx
- config/routes.js
> All routes use plural (back and front)

- assets/js/react/components/common/GrottoAppBar.jsx
- assets/js/react/components/homepage/DonateForm.jsx
- assets/js/react/conf/Config.jsx
> Display issues

- assets/js/react/components/appli/entries/Details.jsx
- assets/js/react/components/common/MapEntryPopup.jsx
> fix(#155): entry details on V2

- api/controllers/v1/GeoLocController.js
- api/controllers/v1/SearchController.js
- api/models/TEntry.js
- api/services/GeoLocService.js
- api/services/MappingV1Service.js
- assets/js/react/actions/Map.jsx
- assets/js/react/components/common/GCMap.jsx
- assets/js/react/components/common/MapGroupIcon.jsx
- assets/js/react/components/common/Searchbar.jsx
- package.json
> fix(#146): map issues

- tasks/config/copy.js
- tasks/pipeline.js
- tasks/register/compileAssets.js
> fix(#143): swagger CSS

- assets/js/react/components/appli/AppToolbar.jsx
> Fix/#168 Update Search Bar look

- LICENSE
I propose the license that was chosen for V2
> Licence for the V3

- .gitignore
- .storybook/main.js
- README.md
- assets/js/react/components/1-Button.stories.js
- commitlint.config.js
- package-lock.json
- package.json
- Add [storybook ](https://storybook.js.org/) dependency
- Add some documentation about Husky hooks (to check commit name and lint) and storybook
@bsoufflet
> Development environment: Storybook utility

- .travis.yml
- README.md
- api/services/MappingV1Service.js
- appspec.yml
- deployProd.sh
- restart_prod.sh
- stop_prod.sh
**This PR contains all the changes required to deploy the GrottoCenter3 application on AWS.** 
The brach should only be added to RC when you want to migrate the application to AWS. 
**If you want to deploy on AWS :** 
- Merge the pull request
- On the .travis.yml configuration file do the following changes : 
- uncomment le line 14 : `#tags: true`
- change the line 15 : `branch: devops_aws` with `branch : rc`
Associated documentation : 
- Deployment of the MySQL database on Amazon RDS: https://docs.google.com/document/d/1nmfGdScWYBWa91L0SRd7LrH5XK_DQKbkGMtVdDQlmgg/edit?usp=sharing 
- Deployment of the Grottocenter3 application on EC2: https://docs.google.com/document/d/1h8cdmlkZJG5SANKLfQQpOR1kNjMQiSKqb-N-LhM1Zlk/edit?usp=sharing 
- Deployment of ElasticSearch and Logstash on Lightsail: …
> Deployment on AWS

- assets/js/react/components/common/SideMenu/MenuLinks.jsx
> FRONT: Sidebar bug on Safari

- api/controllers/v1/SearchController.js
- api/services/MappingV1Service.js
A regression was introduced by converting the Object.assign() function by a spread operator.
> fix(#245): Fix quick search back end 500 error

- assets/js/react/features/QuickSearch.jsx
Fix case 2. referenced here : #267 
There were an error on the url pushed when a bbs is selected.
> Quick Search : fix click on bbs result (typo in URL)

- assets/js/react/components/common/LoginForm/_stories.js
I've made a little mistake when rebasing my previous pull request #274 Authentication... Here is the fix
> Auth Story - Fix an interactive rebase mistake

- api/services/ElasticsearchService.js
> [ADV SEARCH] - Remove single quote from escaped chars

- assets/js/react/components/common/card/RandomEntryCard.jsx
Fix #182 issue
- County / Region / Country text => 1 per line, ellipsis if too long
- Topo img is at least 300px (= responsive breakpoint) or more if possible
**Overview**
**Large resolution layout (img > 300px)**
**Small resolution layout (img < 300px)**
> [RANDOM ENTRY] Improve layout (responsive + text ellipsis)

- assets/js/react/components/homepage/advancedSearch/SearchResultsTable.jsx
It fixes #263 
When clicking on a advanced search result :
- On mobile => push on current tab
- On desktop => open in a new tab
Also, an eslint cleaning on SearchResultsTable component was made.
> [ADV SEARCH] Different result click behaviour (mobile / desktop)

- api/controllers/DocumentController.js
- api/models/TCaver.js
- api/models/TDocument.js
- api/services/MappingV1Service.js
- apiV1.yaml
- bbs column doesn't exist anymore in t_document
- contact_is_public doesn't exist anymore in t_caver
> [PG DB Model] Fixes according to the new PG data model

- assets/js/react/actions/Auth.jsx
- assets/js/react/features/AppBar.jsx
- assets/js/react/helpers/AuthHelper.jsx
- assets/js/react/pages/DocumentSubmission.jsx
- assets/js/react/reducers/AuthReducer.jsx
- Removing authToken is now performed in reducer (instead of in action)
- Don't redirect to home page when logging out => components must handle the disconnection by themselves
- Add some useful features to the AuthHelper
- Adapt the DocumentSubmission component to this new mechanisms
> [CLIENT AUTH SYSTEM] Refactor, improvement and cleaning

- assets/js/react/actions/Auth.jsx
- assets/js/react/helpers/AuthHelper.jsx
- assets/js/react/reducers/AuthReducer.jsx
Simple refactoring & sticking to redux logic (perform modifications in reducer, not in action)
> [AUTH TOKEN] Set auth token in reducer & move setToken in AuthHelper

- assets/js/react/features/AuthChecker/_stories.js
- assets/js/react/features/AuthChecker/index.jsx
- config/locales/en.json
- config/locales/fr.json
The AuthChecker provides a default error message if the user is not authenticated. But you can also use a custom component to display the error.
The Storybook of this component is wired to a Redux store because it listens to it to know if the users has logged in / out.
> [AUTH CHECKER] New component allowing auth conditional displaying of another component

- assets/js/react/components/homepage/advancedSearch/SearchResultsTable.jsx
Document page is in progress : /bbs url no longer works.
> [DOC SEARCH] remove onClick result redirection

- assets/js/react/components/common/Layouts/Main/index.jsx
- assets/js/react/components/common/SideMenu/index.jsx
- assets/js/react/pages/Application.jsx
- config/locales/en.json
- config/locales/fr.json
> fix(#358) - Update side menu login msg when (dis)connected

- api/controllers/GrottoController.js
> fix(#356) [ORGANIZATION DETAILS] Properly set information and catch errors 

- api/controllers/SearchController.js
- api/services/ElasticsearchService.js
- api/services/MappingV1Service.js
- apiV1.yaml
- assets/js/react/components/appli/Document/DocumentForm/formSteps/Step2.jsx
- assets/js/react/features/DocumentAutoComplete.jsx
- assets/js/react/helpers/Entity.jsx
- logstash.conf
If you are submitting an article, search only for an issue.
If you are submitting an issue, search only for a collection.
> [DOC SUBMISSION] Conditionnal "Document parent" search

- api/controllers/CaverController.js
- api/services/CaverService.js
- apiV1.yaml
- assets/js/react/actions/Caver.js
- assets/js/react/components/appli/ManageUserGroups/index.jsx
- assets/js/react/components/common/UserList/index.jsx
- assets/js/react/conf/Config.jsx
- assets/js/react/pages/Admin/ManageUsers.jsx
- assets/js/react/pages/Admin/UserList.jsx
- assets/js/react/pages/Dashboard.jsx
- assets/js/react/reducers/CaverGroupsReducer.js
- assets/js/react/reducers/CaverReducer.js
- assets/js/react/reducers/GCReducer.jsx
- config/locales/en.json
- config/locales/fr.json
- config/policies.js
- config/routes.js
In admin dashboard : 
* Display list of administrators
* Display list of moderators
* Update lists when an user groups have been changed
> [ADMIN DASHBOARD] Add admins and moderators list

- api/services/MappingV1Service.js
- assets/js/react/components/common/card/RandomEntryCard.jsx
Fix #357 
The fix uses the img from the Grottocenter v2 server & the TopographicDrawing id is hardcoded (13). It's not perfect, we will need to change it when we will handle the files and their path properly on the v3.
> fix(#357) [RANDOM ENTRANCE HOME PAGE] Display topo from GC v2 and fix depth & length path

- api/controllers/DocumentController.js
- assets/js/react/components/appli/Document/DocumentForm/formElements/PublicationDatePicker.jsx
- Document  main language is optional on API side (for an Image there is no language)
- For the publication date picker, add translated text ("Ok" and "Cancel")
> [DOC SUBMISSION] Little improvements

- assets/js/react/components/appli/Document/DocumentForm/formElements/DescriptionEditor.jsx
- assets/js/react/components/appli/Document/DocumentForm/formElements/IdentifierEditor.jsx
- assets/js/react/components/appli/Document/DocumentForm/formElements/PagesEditor.jsx
- assets/js/react/components/appli/Document/DocumentForm/formElements/TitleEditor.jsx
- assets/js/react/components/appli/Document/DocumentForm/formSteps/Step3.jsx
- assets/js/react/components/common/Form/StringInput.jsx
- assets/js/react/pages/DocumentValidation/Actions.jsx
- assets/js/react/pages/DocumentValidation/index.jsx
Comment not mandatory
Small refactor on StringInput concerning translation
> [FEAT][FRONT][Doc validation]: Add comment on validation

- assets/js/react/components/appli/Document/DocumentForm/Provider.js
- assets/js/react/components/appli/Document/DocumentForm/index.jsx
- assets/js/react/pages/DocumentSubmission.jsx
Add another Article by keeping some values (parent document, publication date, editor, library, document language, title and description language, document type).
> [DOC SUBMISSION] Add submit another article button

- assets/js/react/pages/DocumentDetails/Overview.jsx
More lisible like this + asked by BBS client
> [DOC DETAILS] Remove title uppercase

- assets/js/react/actions/Entry.js
Add return json in action to put it in redux store properly.
> [ENTRANCE PAGE] Make it work again by fixing action

- api/controllers/CaveController.js
- assets/js/react/actions/Cave.js
>  [CAVE PAGE] Make it work again by fixing action + set names

- api/services/MappingV1Service.js
> fix(#416) [API MAPPING] API Mapping with JSON-LD : add keys @base, @id, @type, @context

- assets/js/react/components/common/SideMenu/Items.js
- assets/js/react/components/common/SideMenu/MenuLinks.jsx
- assets/js/react/components/common/SideMenu/index.jsx
- assets/js/react/helpers/AuthHelper.jsx
- assets/js/react/pages/DocumentSubmission.jsx
**isUser() != isAuth()**
You can be authenticated as an admin but if you are not an user in the database, you can't perform some actions (like submitting a document).
That's why we need to make a distinction between someone authenticated (an user, a moderator or an admin) and someone who is an user.
> [AUTH RENDERING] Add isUser method to AuthHelper

- api/models/TDocument.js
- assets/js/react/components/appli/Document/DocumentForm/Provider.js
- assets/js/react/components/appli/Document/DocumentForm/formElements/PublicationDatePicker.jsx
- assets/js/react/components/appli/Document/DocumentForm/formSteps/DocumentStepsHelper.js
- assets/js/react/components/appli/Document/DocumentForm/formSteps/Step4.jsx
- assets/js/react/components/appli/Document/DocumentForm/types.js
- assets/js/react/components/homepage/advancedSearch/SearchResultsTable.jsx
- assets/js/react/pages/DocumentDetails/index.jsx
- assets/js/react/pages/DocumentEdit/index.jsx
- assets/js/react/pages/DocumentValidation/customCellRenders.js
This allows partial date such as "01-2017" or "2017". 
Feel free to ask me the new database dump with this modification
> [DOCUMENT] Publication date is now a string

- assets/js/react/actions/Advancedsearch.jsx
- assets/js/react/components/homepage/advancedSearch/SearchResultsTable.jsx
I didn't try to clean or improve the code, it's just a fix to make it work again.
> [ADV SEARCH - CSV EXPORT] Fix CSV export (safe get of entrance.cave + use POST method on search URL)

- assets/js/react/features/AppBar.jsx
- assets/js/react/features/Login.jsx
- assets/js/react/hooks/usePermissions.js
I forgot some of them in the previous PR...
> [AUTH REDUX] fix Redux state.auth to state.login

- api/controllers/CaverController.js
- api/controllers/EntranceController.js
- api/controllers/v1/CaverController.js
- api/controllers/v1/EntranceController.js
- assets/js/react/conf/Config.jsx
- config/policies.js
- config/routes.js
[entrances] Use /v1 url
[cavers count] rename "getCaversNumber" by "count"
> [ENTRANCES API] /entrances/count KO 504

- api/controllers/EntranceController.js
> [ENTRANCES API] Hide sensible information on sensitive entrances

- api/controllers/AdminController.js
- api/controllers/CaveController.js
- api/controllers/CaverController.js
- api/controllers/DocumentController.js
- api/controllers/DocumentTypeController.js
- api/controllers/EntranceController.js
- api/controllers/GrottoController.js
- api/controllers/LanguageController.js
- api/controllers/MassifController.js
- api/controllers/PartnerController.js
- api/controllers/RegionController.js
- api/controllers/SubjectController.js
- api/controllers/v1/GrottoController.js
- api/controllers/v1/PartnerController.js
- api/services/EntranceService.js
- apiV1.yaml
- assets/js/react/conf/Config.jsx
- config/routes.js
Voici ma dernière passe de nettoyage de l'API avant que j'attaque toutes les nouvelles fonctionnalités (histoire de commencer sur une base propre :slightly_smiling_face: )
> fix(api): Cleanup and fixing some old invalid  code

- assets/js/react/components/homepage/advancedSearch/SearchResultsTable.jsx
> feat(search): scrolls down to search results

- package-lock.json
- package.json
Close #513 
Close #506 
Close #505 
Close #504 
Close #503
>  [PACKAGES] Update packages & fix Snyk recommendations

- api/controllers/CaverController.js
- api/services/CaverService.js
- assets/js/react/pages/Admin/UserList.jsx
- assets/js/react/pages/Admin/customCellRenders.js
> [GET ADMINS / MODERATORS] #495 : Groups are now returned

- api/controllers/AuthController.js
- api/controllers/CaverController.js
- api/controllers/DocumentController.js
- api/controllers/EntranceController.js
- api/controllers/GrottoController.js
- api/controllers/v1/EntranceController.js
- api/models/TCountry.js
- api/models/TEntrance.js
- api/models/TGeology.js
- apiV1.yaml
- config/policies.js
- config/routes.js
I have also improved the error management on the other "create" api endpoints.
> [ENTRANCE API] Add create entrance API route

- api/controllers/EntranceController.js
- api/controllers/v1/EntranceController.js
- api/models/TEntrance.js
- api/services/ControllerService.js
- api/services/ElasticsearchService.js
- apiV1.yaml
- config/policies.js
- config/routes.js
I already merged this feature in the past weeks but not in the develop branch.
> [ENTRANCE API] Delete entrance api route

- api/controllers/AccountController.js
- api/controllers/v1/AccountController.js
- apiV1.yaml
- config/policies.js
- config/routes.js
I also fixed the changeEmail route. Now, both controller methods have the same logic.
> [ACCOUNT API] Add change alert for news route api

- assets/js/react/components/common/Maps/MapClusters/constants.js
- assets/js/react/components/common/Maps/MapClusters/index.jsx
- assets/js/react/components/common/Maps/MapClusters/useCurrentPosition.js
- assets/js/react/components/common/Maps/MapClusters/useHeatLayer.js
- assets/js/react/components/common/Maps/MapMultipleMarkers/index.jsx
- assets/js/react/components/common/Maps/_stories.js
- assets/js/react/components/common/Maps/common/Markers/Components/EntrancePopup.jsx
- assets/js/react/components/common/Maps/common/Markers/Components/LocationMarker.jsx
- assets/js/react/components/common/Maps/common/Markers/Components/NetworkPopup.jsx
- assets/js/react/components/common/Maps/common/Markers/Components/OrganizationPopup.jsx
- assets/js/react/components/common/Maps/common/Markers/Components/Title.jsx
- assets/js/react/components/common/Maps/common/Markers/Components/utils.js
- assets/js/react/components/common/Maps/common/Markers/useMarkers.js
- assets/js/react/components/common/Properties/Property.jsx
**Feat:**
- Different styles on hex depending on zoom. The point is to better see the hex when we are closer _(when zoom > 8)_
**Bug fix:**
- No more breaking CSS. The bug appeared when map markers were visible. A rework on markers popup did the fix _(also add stories for popup)_
- Hex now correctly change color & size on **zoom in** (now zoom in always do an api call. It's necessary to update data for colorScale & sizeScale)
> [MAP] Fix & Improvement

- api/controllers/CaveController.js
- api/controllers/v1/CaveController.js
- api/models/TCave.js
- api/models/TMassif.js
- api/services/MappingV1Service.js
- api/services/mappingModels/CaveModel.js
- apiV1.yaml
- config/policies.js
- config/routes.js
I had to change the TCave model due to a Sails issue (see here : [https://github.com/balderdashy/sails/issues/7106](https://github.com/balderdashy/sails/issues/7106)).
> [CAVE API] Add create cave api route

- assets/js/react/pages/DocumentDetails/index.jsx
- assets/js/react/pages/DocumentDetails/transformers.js
> [DOCUMENT DETAILS] display bbs legacy publication data

- api/controllers/EntranceController.js
Error spotted by @luc-RAYMOND, thanks !
> [ENTRANCE API] Fix location creation (incorrect fields)

- assets/js/react/components/appli/Document/DocumentForm/formElements/PagesEditor.jsx
> [DOC SUBMISSION] Allow endPage equal to startPage

- assets/js/react/components/appli/Document/DocumentForm/formElements/PublicationDatePicker.jsx
> [DOC SUBMISSION] handle null publicationDate value

- api/controllers/CaverController.js
- api/controllers/v1/CaverController.js
- api/services/CaverService.js
- assets/js/react/components/homepage/WhatIsIt.jsx
- assets/js/react/conf/Config.jsx
- config/policies.js
- config/routes.js
> [HOME PAGE DYNAMIC NUMBERS] Fix number of Grottocenter users

- sql/mock_data.sql
Production database has been updated
> [NAME API] Fix: allow any user to edit any name

- api/controllers/LocationController.js
- api/controllers/v1/LocationController.js
- apiV1.yaml
- config/policies.js
- config/routes.js
- sql/mock_data.sql
- Any user can create a location.
- body, language and entrance are mandatory.
- title is facultative.
> [LOCATION API] Create location api route

- api/controllers/DocumentController.js
- api/controllers/DocumentTypeController.js
- api/models/TType.js
- assets/js/react/components/homepage/advancedSearch/AdvancedSearch.jsx
- assets/js/react/components/homepage/advancedSearch/DocumentSearch.jsx
- assets/js/react/containers/AdvancedSearchContainer.jsx
- assets/js/react/reducers/DocumentTypeReducer.jsx
- logstash.conf
- sql/0_tables.sql
- sql/mock_data.sql
> [ADV SEARCH] Add search by contributor nickname and document type

- api/controllers/EntranceController.js
- api/services/MappingV1Service.js
- api/services/mappingModels/EntranceModel.js
- api/services/mappingModels/MassifModel.js
- apiV1.yaml
Some minor fixes about the findEntrance() and the entrance mapping service functions.
> [FIND ENTRANCE API] Return more populated data (massif, cave, author) & mapping service clean up

- api/controllers/AuthController.js
- api/controllers/CaveController.js
- api/controllers/CaverController.js
- api/controllers/DescriptionController.js
- api/controllers/DocumentController.js
- api/controllers/EntranceController.js
- api/controllers/GrottoController.js
- api/controllers/LocationController.js
- api/controllers/MassifController.js
- api/controllers/NameController.js
- api/services/CaveService.js
- api/services/CaverService.js
- api/services/DocumentService.js
- api/services/EntranceService.js
- api/services/ErrorService.js
- api/services/GrottoService.js
- test/fixtures/tcaver.json
- test/fixtures/tgroup.json
- test/integration/1_services/CaverService.test.js
I tried to test a lots of features in order to be sure nothing is broken but don't hesitate to test on your computer too! 
In this PR, you will also find 2 minor fixes checking if a document / massif is found before populating it (the case were it was not found was not handled).
> [ERROR HANDLING] Improve default error handler & refactor

- api/controllers/SearchController.js
- api/services/ElasticsearchService.js
- api/services/MappingV1Service.js
- apiV1.yaml
- logstash.conf
Elasticsearch instance in production already updated.
> [SEARCH CAVES] Add search on caves using Elasticsearch

- api/controllers/v1/SwaggerController.js
- assets/swaggerV1.yaml
- config/policies.js
- config/routes.js
Fix #651
Route : `GET api/v1/swagger.yaml`
File name and location : `assets/swaggerV1.yaml`
> [DOC] Swagger yaml endpoint

- api/services/ElasticsearchService.js
- test/integration/1_services/ElasticsearchService.test.js
The previous function was not working: String.replace() doesn't mutate the String !
> [QUICKSEARCH] fix sanitizeQuery and add test

- api/controllers/DocumentController.js
> [DOC CSV IMPORT] Find parent by id instead of title

- api/helpers/distant-file-download.js
- test/integration/2_helpers/DistantFileDownload.test.js
> [FILE DOWNLOAD] Accept http protocol

- README.md
- api/controllers/DocumentController.js
- test/integration/3_routes/Document.test.js
Fix #668
The result was treated as a single document instead of an array.
> [FIND MY DOCS] Fix it by iterating over documents

- api/controllers/DocumentController.js
> [DOC CSV IMPORT] Make dct:creator facultative

- api/controllers/DocumentController.js
- api/services/DocumentService.js
> [DOC CREATION] Parent doc is mandatory for issues & articles

- api/controllers/CaveController.js
- api/controllers/EntranceController.js
- api/models/TCave.js
- api/models/TEntrance.js
- api/models/THistory.js
- api/services/MappingV1Service.js
- api/services/mappingModels/CaveModel.js
- api/services/mappingModels/EntranceModel.js
- test/bootstrap.test.js
- test/fixtures/tcave.json
- test/fixtures/thistory.json
- test/integration/3_routes/Cave.test.js
> [HISTORY] Add history data to cave and entrance

- api/controllers/v1/OptionController.js
- api/models/TLicense.js
- config/policies.js
- config/routes.js
- test/bootstrap.test.js
- test/fixtures/tfileformat.json
- test/fixtures/tlicense.json
- test/fixtures/toption.json
- test/integration/3_routes/FileFormat.test.js
- test/integration/3_routes/IdentifierType.test.js
- test/integration/3_routes/License.test.js
- test/integration/3_routes/Option.test.js
- test/integration/3_routes/Organization.test.js
Let's continue on the infinite road to 100% tests coverage!
> [TESTS] Add more tests

- docker/sample.env
> [ELASTICSEARCH & LOGSTASH] Bump version

- sql/2_2021_09_22_6_licenses.sql
Fix #684
La prod est déjà à jour, pas besoin de déployer pour que ça fonctionne normalement.
> [LICENSES] Add CC-BY-NC-ND license

- api/controllers/EntranceController.js
- api/services/DocumentService.js
- api/services/MappingV1Service.js
> [ENTRANCE DOCS] Populate entrance docs data

- api/controllers/EntranceController.js
> [ENTRANCE DESCRIPTIONS] Populate entrance description author

- api/services/DocumentService.js
Fix #698
La requête SQL renvoyait les ids des enfants dans un ordre plus ou moins aléatoires. Quand on itérait dessus, on comptait sur le fait d'avoir itéré sur un enfant AVANT d'itérer sur le petit-enfant. Or ce n'était pas toujours le cas. 
Désormais on itère d'abord sur tous les enfants puis on les complète avec les petits-enfants.
> [DOC CHILDREN] Populate all grand child docs

- api/controllers/MassifController.js
- api/controllers/NetworkController.js
- api/controllers/v1/NetworkController.js
- api/services/CaveService.js
- api/services/MappingV1Service.js
- api/services/MassifService.js
- api/services/NetworkService.js
- api/services/mappingModels/MassifModel.js
- test/integration/3_routes/Massif.test.js
> [MASSIF] Return entrances & networks instead of caves

- .github/workflows/build.yaml
- api/models/HDescription.js
- api/models/HDocument.js
- api/models/TCave.js
- api/models/TCaver.js
- api/models/TComment.js
- api/models/TDescription.js
- api/models/TDocument.js
- api/models/TEntrance.js
- api/models/TFile.js
- api/models/TGrotto.js
- api/models/THistory.js
- api/models/TLocation.js
- api/models/TMassif.js
- api/models/TName.js
- api/models/TPoint.js
- api/models/TRigging.js
- config/datastores.js
- docker/docker-compose.yml
- docker/sample.env
- test/bootstrap.test.js
- test/fixtures/tgrotto.json
- test/fixtures/tgroup.json
- test/integration/1_services/DescriptionService.test.js
- test/integration/3_routes/Document.test.js
- test/integration/3_routes/Massif.test.js
Close #634
For both development and github pull requests, an empty database is created for the tests. This will allow us to test everything, including transactions and native queries !
> [TESTS] Run test using a test database

- sql/2_2021_09_22_6_licenses.sql
- test/fixtures/tlicense.json
Fix #718
Production database already updated, it should already work.
> [LICENSES] Add licenses

- api/controllers/DocumentController.js
> [DOC validation] Fix access to language when validating a document

- api/controllers/DocumentController.js
- api/services/DescriptionService.js
- test/integration/1_services/DescriptionService.test.js
> [DOC edition] Parent edition doesn't display name correctly

- api/services/DocumentService.js
- api/services/MappingV1Service.js
Related to https://github.com/GrottoCenter/grottocenter-front/issues/353
> fix(docDupMapping): mapping now handle different content cases

- api/controllers/v1/document/find-all.js
- api/controllers/v1/document/find-by-caver-id.js
- api/controllers/v1/document/find.js
- api/services/DocumentService.js
Fix https://github.com/GrottoCenter/grottocenter-front/issues/380
See https://github.com/GrottoCenter/grottocenter-front/issues/380
> [DOCUMENT] Change the way mainLanguage of a doc is computed

- api/services/CaverService.js
- api/services/MappingV1Service.js
- test/fixtures/tcaver.json
- test/fixtures/tentrance.json
- test/integration/1_services/CaverService.test.js
- test/integration/3_routes/Cavers/find.test.js
- test/integration/3_routes/Cavers/usersCount.test.js
> 770 person view

- api/controllers/v1/entrance/import-rows.js
- api/services/CaveService.js
- api/services/DocumentCSVImportService.js
- api/services/EntranceCSVImportService.js
- config/constants/karstlink.js
- test/integration/1_services/CaveService.test.js
Fix #763
And refactor Karstlink constants
> [ENTRANCE CSV IMPORT] fix language and date handling

- api/services/CaverService.js
- api/services/MappingV1Service.js
- test/integration/1_services/CaverService.test.js
- test/integration/3_routes/Cavers/find.test.js
> feat(#796): getCaver return the mail for admin and user logged

- logstash.conf
- sql/2_2021_09_22_5_languages.sql
Fix #801
Prod already updated with this file: 
[liste_des.langues_officielles_parlees_dans_au_moins_un_pays.csv](https://github.com/GrottoCenter/Grottocenter3/files/8510975/liste_des.langues_officielles_parlees_dans_au_moins_un_pays.csv)
Also, add a non prefered language to sql mock data.
> [ES LANGUAGES] Index only prefered languages

- api/controllers/v1/organization/create.js
> fix(855): language is missed when create name

- api/controllers/v1/cave/delete-one.js
- api/controllers/v1/entrance/move-to-cave.js
- api/models/TCave.js
- api/services/CaveService.js
- assets/swaggerV1.yaml
- config/policies.js
- config/routes.js
- test/integration/3_routes/Entrances/FAKE_DATA.js
- test/integration/3_routes/Entrances/moveToCave.test.js
> 852 [ENTRANCE EDIT] Change cave

- api/controllers/v1/massif/update.js
- api/services/MassifService.js
- assets/swaggerV1.yaml
- test/integration/3_routes/Massifs/update.test.js
add id in the parameters of update massif
> fix(453): add id to massif update

- api/controllers/v1/account/change-password.js
Resolve #870
modification du changement de mot de passe pour prendre en compte le token d'authentification si l'utilisateur est connecté.
> improvement(870): authToken change password

- api/controllers/v1/document/create.js
- api/controllers/v1/document/find.js
- api/controllers/v1/document/update.js
- api/services/FileService.js
- Improve error management of file update & creation (delete eslint-disable, use a custom exception)
- Fix case-sensitive file extension check
- When getting an edited document, safely get optional data
> [DOCUMENTS] Various fixes about editing & files

- README.md
- api/controllers/v1/entrance/find.js
- api/controllers/v1/rigging/update.js
- api/models/TRigging.js
- api/services/CommentService.js
- api/services/MappingService.js
- api/services/RiggingService.js
- test/integration/1_services/RiggingService.test.js
- better handle entrance average ratings (do not use 0/null rating)
- Properly handle updating rigging with no lines (empty obstacles)
- add missing dateReviewed in TRigging
- improv doc for prod deploy
fix #1049
> fix(rigging): fix response format to create/update request

- config/http.js
Add an INFO log for each HTTP request which arrive on the API
We need it for better troubleshooting of problematic requests
> feat(log): add info log for each HTTP request

- assets/swaggerV1.yaml
- config/http.js
- package-lock.json
- package.json
also prepare version number v22.0.31 for next release
In addition to logging the HTTP request when it arrive on the API, we want to log the response status code of the API and the time spend to process the request.
> feat(log): add response status and timing for each request

- api/services/DescriptionService.js
- api/services/EntranceService.js
- api/services/RiggingService.js
_Fix test on snapshots don't pass.
_Change EntranceService to adapt with setNames function
> fix(improve): fix error 500 due to setName remove

- test/integration/4_routes/Massifs/get-statistics.test.js
Delete test 
The test logic was not good, it was testing the data which was stored in the view, instead of testing the code of the feature itself. It was not relevant to keep it.
> test(getStatistics): delete test

- api/controllers/v1/country/get-statistics.js
- api/services/StatisticsCountryService.js
- assets/swaggerV1.yaml
- config/policies.js
- config/routes.js
- cron/refresh_views_procedure.sh
- sql/4_materialized_views.sql
- sql/4_refresh_views.sql
Add the request to get data statistics of a country : 
- Creation of a view to compute the values faster
- Creation of a service to request the view 
- Creation of the controller and the route
> Get data statistics of a country 

- api/controllers/v1/document/get-snapshots.js
- api/controllers/v1/entrance/get-all-snapshots.js
- api/controllers/v1/location/get-snapshots.js
- api/models/HDocument.js
- api/services/DocumentService.js
- api/services/EntranceService.js
- api/services/LocationService.js
- assets/swaggerV1.yaml
- config/policies.js
- config/routes.js
Add a route for the general page of snapshot. 
It contains all snapshots related to an entrance (Entrances, Locations, Descriptions, ...)
> Get all snapshots of an entrance

- api/controllers/v1/cave/cumulated-length.js
- api/controllers/v1/country/count.js
- api/services/CaveService.js
- api/services/CountryService.js
- assets/swaggerV1.yaml
- config/policies.js
- config/routes.js
- test/integration/4_routes/Caves/cumulated-length.test.js
- test/integration/4_routes/Countries/count.test.js
Added request to get the number of countries available in the web site and the cumulated length of all caves.
> feat(HomepageData): get nb countries and cumulated length

- api/controllers/v1/country/get-entrances-data-quality.js
- api/controllers/v1/massif/get-entrances-data-quality.js
- api/services/DataQualityComputeService.js
- api/services/StatisticsCountryService.js
- api/services/mapping/converters.js
- api/utils/computeEntranceDataQuality.js
- assets/swaggerV1.yaml
- config/policies.js
- config/routes.js
- cron/refresh_data_quality_view_procedure.sh
- package-lock.json
- package.json
- sql/4_materialized_views.sql
- sql/4_refresh_views.sql
- test/integration/4_routes/Countries/get-entrances-data-quality.test.js
- test/integration/4_routes/Countries/get-statistics.test.js
Added routes to get entrances of a massif or a country. We computed the quality of the data registered for each entrances. 
We created a new file in the utils folder to put the different functions use to compute the quality of the data.
> entrance-quality-data

- api/services/GeoLocService.js
- assets/swaggerV1.yaml
better entrances format for geoloc API
Make it compatible with the mobile app
Make it compatible with the current schema which has no more single entrances (SE)
> fix(geoloc): better entrances format for geoloc API

- api/controllers/v1/entrance/get-all-snapshots.js
- api/controllers/v1/entrance/get-snapshots.js
- api/services/EntranceService.js
- assets/swaggerV1.yaml
- test/integration/4_routes/Snapshots/get-snapshots-entrances.test.js
Modifications in the services to implement restore snapshot feature.
Create snapshot restore feature.
Modify the entrance service to adpat it to restore an entrance version.
> feat(dataHistory): restore snapshot

- api/controllers/v1/comment/update.js
Should fix https://github.com/GrottoCenter/grottocenter-front/issues/867
> fix(comment): cannot unset ratings or durations from comments

- api/services/StatisticsCountryService.js
- api/services/StatisticsMassifService.js
> fix(country): wrong length and depth statistics

- api/services/DocumentService.js
- api/services/EntranceCSVImportService.js
- Fix entrance CSV import: #1145
- Missing author in document duplicate: part of [grottocenter-front/812](https://github.com/GrottoCenter/grottocenter-front/issues/812)
> Fix entrance CSV import + Missing author in document duplicate 

- api/controllers/v1/description/update.js
- api/controllers/v1/document/update-with-new-entities.js
- api/controllers/v1/entrance/get-all-snapshots.js
- api/controllers/v1/entrance/move-to-cave.js
- api/controllers/v1/entrance/update-with-new-entities.js
- api/controllers/v1/organization/update.js
- api/controllers/v1/rigging/update.js
- api/services/DocumentService.js
- api/services/NotificationService.js
- test/integration/4_routes/Caves/addDocument.test.js
- test/integration/4_routes/Caves/update.test.js
- test/integration/4_routes/Entrances/update.test.js
Fix lint issues introduced after packages update
> Fix lint issues
